apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-server
  template:
    metadata:
      labels:
        app: flask-server
    spec:
      containers:
      - name: flask-server
        image: ancaco12/mock-server-flask:v6
        ports:
        - containerPort: 5000 # puerto del contenedor
        env:
        - name: USERNAME
          valueFrom: # este valor viene de un secret
            secretKeyRef:
              name: my-secret # nombre del secret
              key: MYSQL_USER
        - name: USER_PASSWORD 
          valueFrom: # este valor viene de un secret
            secretKeyRef:
              name: my-secret # nombre del secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: MYSQL_DATABASE
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: MYSQL_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: flask-server
spec:
  type: ClusterIP
  selector:
    app: flask-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      # nodePort: 30100 # puerto del servicio, puede ser cualquiera entre 30k y 32767
