# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv
#   labels:
#     type: local
#     app: mysql
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 400Mi
#   accessModes:
#     - ReadWriteOnce
  # hostPath:
  #   path: "/persistent_init_scripts/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    app: mysql
    name: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: standard
  # volumeName: pv